# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-17 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thelist', '0003_auto_20160417_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='iam_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lon',
            field=models.FloatField(default=0),
        ),
    ]
